version: '3.9'

volumes:
  pgdata:

services:
  backend:
#    env_file:
#      - .env
    build: .
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code/static
    depends_on:
      - postgres
  postgres:
    image: 'postgres'
#    ports:
#     - '5431:5432'
    env_file:
      - .env
#    environment:
#      - POSTGRES_DB=netology_stocks_products
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./:/docker-entrypoint-initdb.d
      - ./logs:/var/logs
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend