POST  http://127.0.0.1:8000/demo/

###
GET http://127.0.0.1:8000/demo/

###

GET http://127.0.0.1:8000/weapon/

###ok

POST http://localhost:8000/api/v1/products/
Content-Type: application/json

{
  "title": "Пом11идор",
  "description": "Лучшие помидоры на рынке"
}
###ok
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

###ok


PATCH http://localhost:8000/api/v1/products/2/
Content-Type: application/json

{
  "description": "Сам!е сочные и ароматные помидорки"
}
###ok
# удаление продукта

DELETE http://localhost:8000/api/v1/products/2/
Content-Type: application/json

###ok
# поиск продуктов по названию и описанию
GET http://localhost:8000/api/v1/products/?search=помидор
Content-Type: application/json

###
# создание склада ok
POST http://localhost:8000/api/v1/stocks/
Content-Type: application/json

{
  "address": "мой адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 4,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 4,
      "quantity": 100,
      "price": 180
    }
  ]
}

###
###

# поиск складов, где есть определенный продукт
GET http://localhost:8000/api/v1/stocks/?products=4
Content-Type: application/json
###
GET http://localhost:8000/adv/

###

POST http://localhost:8000/adv/
Content-Type: application/json

{
  "user": 2,
  "text": "Объявление"
}

###

POST http://localhost:8000/adv/
Content-Type: application/json
Authorization: Token 1f8d170656cdac5e6bc76a52d3c2abcc6e7142a3

{
  "text": "йОбъявление"
}
###

DELETE http://localhost:8000/adv/1/

###
@baseUrl = https://localhost:8000/api
# получение объявлений
GET http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token 309866013bc2587df3fe9daba416f479a826a5c9

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}
