# Generated by Django 4.2 on 2023-05-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_rename_measurements_measurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('created_at', 'temperature')},
        ),
    ]
