# Generated by Django 4.2 on 2023-06-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_alter_measurement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('temperature', 'created_at')},
        ),
    ]
