# Generated by Django 4.2 on 2023-06-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_alter_measurement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'показания'},
        ),
    ]
