# Generated by Django 4.2 on 2023-06-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_alter_measurement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Показания'},
        ),
    ]
