# Generated by Django 4.2 on 2023-05-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together={('order', 'product')},
        ),
    ]
